spring:
  datasource:
    username: firstTask
    password: firstTaskPass
    url: jdbc:mysql://localhost:3306/first-task?useSSL=false&?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect


server:
  port: 9099

project:
  url: localhost:9099
  security:
    access-token:
      length: 64
      symbols: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
      max-count: 10
  image-folder: /first-task/images

logging:
  path: /first-task/log
